### ISSUE TITLE
Loading new game while playing?

### ISSUE THREAD

**Issue by Chromagram** [MiSTer-devel/MegaCD_MiSTer#100]
Once a game is loaded and in-play, I swear I used to be able to just load a new game directly and it would reload back to the BIOS to launch into the new game. However, if I load a new game while a game is in play, it seems to do nothing but kill the audio of the current game, which it leaves open. Is this correct behaviour or is there something wrong?

Perhaps I'm remembering my prior experiences with the core wrong, but I swear you could just load a new game like the other MiSTer cores without having to reset the entire core or reset it/eject disc and start over.

Many thanks.

**Comment by Chromagram** [comment]
Okay, I did get recommended from another source to try a region-free BIOS and that fixed it. 

Can I revise the question then? Once the game is loaded and in-play, I swear I used to be able to just load a new game directly and it would reload back to the BIOS to launch into the new game. However, if I load a new game while a game is in play, it seems to do nothing but kill the audio of the current game, which it leaves open. Is this correct behaviour or is there something wrong?

Perhaps I'm remembering my prior experiences with the core wrong, but I swear you could just load a new game like the other MiSTer cores without having to reset the entire core or reset it/eject disc and start over.

**Comment by pa-august** [comment]
If you are like me and recently switched to CHD I think we are experiencing the same thing: it's because the core expects each game to be in its own subdirectory. I don't know if there are other possible negative consequences besides simply having to Reset and Eject Disk between games, hopefully someone can weigh in on that.

**Comment by pa-august** [comment]
I'm not very technical but I managed to google a bash script to move all of my chds into their own subdirectory, solving the issue.

Apparently the PSX core generates save games names based on directory, so keeping them all in one big directory would be disastrous. Don't know if the MegaCD core does something similar.

**Comment by sorgelig** [comment]
Right, ISO files in same folder are treated as disks of the same game, so swapping them won't reset the system. It's better to have each game in separate folder because some other features (like per-game BIOS or cheats) are also use this scheme.
You still can use several disks in same folder, but you need to reset the core after swapping the disks.

**Comment by Chromagram** [comment]
@sorgelig Many thanks for the clarification, works like a charm. 👍  I'll close out this thread.
