### ISSUE TITLE
Request: MD+ support

### ISSUE THREAD

**Issue by protogem2** [MiSTer-devel/MegaCD_MiSTer#102]
If this has been answered before apologies, I was unable to find any open or closed issues regarding this here or on the Genesis core's github page.

MSU-MD is working fine and it is nice to have it, but it lacks some of the features of MD+ (which ironically make it closer to MSU-1 than MSU-MD is in functionality) and it would be nice to see it supported as it seems a majority of the community have chosen it over MSU-MD and there are many hacks using it now.

Emulators have implemented it as a mapper, perhaps the same approach would work for MiSTer. The Developer document from Terraonion states that it is compatible/uses the Mega CD hardware so I assumed this would be the correct place to post this request.

**Comment by birdybro** [comment]
I don't see any evidence that MD+ is preferred over MSU-MD by the community. It seems to me that there are more MSU-MD patches than MD+ ones, by going off what I'm seeing on zeldix.net ...

MD+ does things that original hardware can't do without an external aftermarket add-on that has RAM and an ARM processor on-board. Here's how ekeeke did it in genesis-plus-gx as a software emulator example for documentation.

https://github.com/ekeeke/Genesis-Plus-GX/issues/297#issuecomment-918468508

If someone were to do this, the above information may be helpful. An OSD option would likely need to be added for this since the MD+ format from TerraOnion bafflingly doesn't have any way of simply indicating that it's MD+ instead of MSU-MD (a very strange deliberate decision...). The MegaSD uses an ARM processor to assist the Mega CD with handling this. The key differences from MSU-MD appear to be:

* Loop point specification in the Cue is possible in addition to the rom patch. Not sure how feasible this would be to implement support for it, but it would likely only need a change in Main I think? @zakk4223 might know the most about the feasibility of this, I'm pretty sure he's looked into this before...
* MegaSD Enhanced SSF2 Mapper - 8MB ROM bankswitching just like the current SSF2 Mapper except you can also use them as RAM for savestates, this might not be feasible on the Cyclone V we use, depending upon the read/write cycle times when used as RAM that is expected by the spec. It's kind of weird though, is there any game actually utilizing the differences between their MegaSD Enhanced SSF2 Mapper and the actual SSF2 Mapper? It might not be worth worrying about.

**Comment by Relikk** [comment]
I'd certainly be lending my support for MD+ implementation in MiSTer.

Both standards have their place as it stands*, but we (Zeldix) would certainly favour MD+ over MSU-MD, as it's more MSU1-like than MSU-MD. Mainly because of the seamless looping audio capability. This is an important feature, and something that isn't possible with MSU-MD. Even Krikzz saw the benefits of this and implemented MD+ into his Mega Everdrive Pro.

There are currently 38 games that utilise MD+. There may be more MSU-MD patched games out there, but a lot of them are still essentially in beta since they were released and are buggy because ArcadeTV never fixed them before he nuked his GitHub. He has returned to the scene recently and is now catering to both formats, which should be encouraged.

_*Use MD+ for MegaSD, Mega Everdrive Pro and Genesis Plus GX. Use MSU-MD for MiSTer and X series Everdrive's with a CD unit._

**Comment by birdybro** [comment]
After a discussion with you and the TerraOnion people, just to reiterate, I have no authority over this, was just offering my personal opinion. Sorry if it came across wrong.

**Comment by protogem2** [comment]
It would be very nice to see MD+ implemented, and I certainly hope any politics involved would not stop this from happening as this is a desirable feature for the MiSTer platform for many.

**Comment by birdybro** [comment]
There aren't politics involved at all here.

@Relikk Does the timing of the data transfer for MD+'s looping require instantaneous data transfer? Given that this core (unlike the SNES core) already has a FIFO for data transfer with delays similar to the original MegaCD do you see that being a problem?

**Comment by Relikk** [comment]
I'm really not the person to ask, but on the MegaSD I **think** there's a one or two frame buffer (reading ahead 588 or 1176 samples) to ensure there are no skips when it loops back around to the specified value in the CUE file.
