### ISSUE TITLE
Feature request - support for MSU-MD track fading and looping

### ISSUE THREAD

**Issue by mario-64** [MiSTer-devel/MegaCD_MiSTer#52]
Please add support for track looping and fading. This is especially noticeable on Ys III MSU-MD. When entering or exiting a house you get a proper track fade on MED Pro but not MiSTer. Also when a track finishes playing on MiSTer it does not loop and start playing again. You just get silence.

**Comment by ekeeke** [comment]
Track looping in MSU-MD driver works by checking absolute time reported in CDD status while NOP commands (0x00) are constantly being sent, however Mister CDD emulation code seems to be copied from Genesis Plus GX emulation code, which did not initially cared about updating the reported time when such commands are sent (mostly because Mega CD bioses do not use this command to read elapsed time and all Mega CD games so far use bios functions to interface with CD hardware).

At first glance, the code that needs to be fixed is here: https://github.com/MiSTer-devel/Main_MiSTer/blob/master/support/megacd/megacdd.cpp#L447

Here is the commit that fixes the same issue in Genesis Plus GX, both code are quite similar so it should be straight-forward to fix it in Mister:
https://github.com/ekeeke/Genesis-Plus-GX/commit/be0edd898cea95f3b4e9aee975ce6485ed65d8b6

**Comment by mario-64** [comment]
Excellent thank you! Not sure who updates the Mega CD core but it would be great to have this added :)

**Comment by mario-64** [comment]
Bumping in hopes a dev can get this added to the core.

**Comment by birdybro** [comment]
This can be closed now as it was fixed --> https://github.com/MiSTer-devel/Main_MiSTer/commit/3df02e631c5e2fb99b30cb5f8dd562c886bb02d6
