### ISSUE TITLE
Lunar intro missing video. Audio works.

### ISSUE THREAD

**Issue by patjohnny** [MiSTer-devel/MegaCD_MiSTer#59]
Lunar silver star story is missing video on intro. Sound works. Final fight has the same problem. Confirmed with another user on discord. Thanks.

**Comment by birdybro** [comment]
This is new then for some reason. Just like a week ago I played lunar silver star story, redump matching hash. Maybe a recent change related to the chd handling? What's the hashes for the files you are using and what bios are you using? Just want to test when I get home.

**Comment by patjohnny** [comment]
Us bios 2.00. Sorry I don’t know the rom. Came from redump. It worked for me a couple weeks ago and I just noticed the problem today. You’re probably right about being related to chd update. Thanks.

**Comment by patjohnny** [comment]
Another user says it works when using the chd of the rom but not bin/cue. Just an FYI.

**Comment by birdybro** [comment]
Steps I'm taking to test:

1. Run update_all to ensure everything is up to date.
2. Freshly transfer all 3 versions of Lunar - The Silver Star that match redump and test all of them, to see if it's just one of the revisions that has an issue (not likely but just to be sure).
3. Copy over a new boot.rom that is specifically Sega CD 2 - 2.00 (USA) bios (not 2.00w or anything like that, and definitely not the oliveira region free bios either) since I normally use theypsilon's update-all script and want to rule out all that first.

Yup it has the same bug in this scenario both on latest release and latest in all versions of the game. Video never restores, and if you click start the audio goes nuts in one version. Now... if I go back to the BIOS I was using, same thing. 

This change is probably related to the recent update to MiSTer_Main. Since the previous release, there were a lot of things added here and there which could be inadvertently affecting cd playback for sure.

**Comment by birdybro** [comment]
https://github.com/MiSTer-devel/Main_MiSTer/issues/324#issuecomment-756547170 - update on my followup. Worked with Rysha, she investigated, reverted a commenting of a line, compiled the binary for me, I tested it. Reverting this comment broke CHD, but restored CUE/BIN functionality. OSD sound bugs occurred previously as well, and those no longer happen. But CHD runs at like 2x speed for CD audio.
