### ISSUE TITLE
Auto Cart Region option changes aspect ratio.

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/MegaCD_MiSTer#67]
There appears to be a bug where this feature is tied to the aspect ratio.

**Comment by sorgelig** [comment]
I'm thinking to remove Auto Cart Region feature.

**Comment by iequalshane** [comment]
I had almost removed it as part of my change but thought maybe there was some use I hadn't thought of. This was working when I tested before we merged so maybe this happened when the framework came in.

**Comment by sorgelig** [comment]
i've reworked it, so it's more natural now.

**Comment by iequalshane** [comment]
I'm not certain this change is quite right. There are multi-region codes in the header like "JUE", which is why the Genesis core has a priority list. Since MegaCD already has a region setting, I wonder if it's easier just to remove auto-region entirely and use whatever the console is set to. Then again, we probably want to get closer to convergence with the Genesis core.

**Comment by sorgelig** [comment]
MegaCD is made primarily for CD games where BIOS determines the region. And it works as expected without needing change of region manually.
