### ISSUE TITLE
Lunar 2 no longer booting

### ISSUE THREAD

**Issue by SwedishGojira** [MiSTer-devel/MegaCD_MiSTer#72]
The files I have of the game are no longer booting. Neither the original dump or the "un-worked designs". The files worked perfectly a week ago and the same files boot non my PC after transferring them from the MiSTer's SD card.

**Comment by aihooo444** [comment]
I can confirm this issue.

**Comment by mario-64** [comment]
Confirming the issue as well

**Comment by birdybro** [comment]
Does switching the region change the behavior?

**Comment by aihooo444** [comment]
> Does switching the region change the behavior?
No I just tried all three regions and no luck you get a blue screen saying cant play in that region also i have tried all the different bios available for usa and it does not help it.

**Comment by mario-64** [comment]
I reverted to the June 2020 Mega CD core. Now it's working fine. Will remain there until the devs get all this fixed.

**Comment by birdybro** [comment]
I tested a few other games, and confirmed same behavior from lunar 2 eternal blue. 

Mortal Kombat: resets the system after the fmv is loaded and you skip it or let it finish. 

Sonic megamix: won't load the first stage (did it never work? I can't remember)

That's all I noticed out of about 30 games I booted to see if the problem was wide spread.

**Comment by henryrizzi** [comment]
This issue will be resolved with the next release. The most recent commit reverted the timer interrupt fix that was put in after the June release. #74 is the PR that was merged for the revert.

**Comment by aihooo444** [comment]
This is now fixed.

**Comment by birdybro** [comment]
This can be closed.
