### ISSUE TITLE
Robo Aleste slowdown

### ISSUE THREAD

**Issue by meauxdal** [MiSTer-devel/MegaCD_MiSTer#73]
Robo Aleste seems to be exhibiting inaccurate slowdown

https://viewsync.net/watch?v=cq0xx8-D1Ug&t=32.43&v=IOa8m2zOtBs&t=289.32

Using Redump image. The latest build I was able to test that did not exhibit this slowdown is MegaCD_20200620.rbf.

**Comment by arobotbitme** [comment]
Ran into the same issue:

MiSTer v210109
128MB RAM (Mister Add-ons)
Standard I/O

Tried it across various rips and regionalities (confirmed the issue is present in Dennin Aleste (J)) as well as across various versions of Mega CD BIOS (US Model 2 as well as region-free Model 2).

MegaCD_20200620.rbf is the most recent version that runs at normal speed.

**Comment by henryrizzi** [comment]
This slowdown also appears to be related to the timer interrupt. Next release should fix the issue, as the most recent commit reverted those changes.

**Comment by aihooo444** [comment]
This is fixed

**Comment by M-Walrus** [comment]
Commenting to clarify that this issue seems to be occurring again in latest build after timer fix rollback.
